/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */


import { GraphQLContext } from "./../context"
import { FieldAuthorizeResolver } from "nexus/dist/plugins/fieldAuthorizePlugin"


declare global {
  interface NexusGenCustomOutputProperties<TypeName extends string> {
    model: NexusPrisma<TypeName, 'model'>
    crud: any
  }
}

declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
  BoolFilter: { // input type
    equals?: boolean | null; // Boolean
    not?: NexusGenInputs['NestedBoolFilter'] | null; // NestedBoolFilter
  }
  CommentListRelationFilter: { // input type
    every?: NexusGenInputs['CommentWhereInput'] | null; // CommentWhereInput
    none?: NexusGenInputs['CommentWhereInput'] | null; // CommentWhereInput
    some?: NexusGenInputs['CommentWhereInput'] | null; // CommentWhereInput
  }
  CommentWhereInput: { // input type
    AND?: NexusGenInputs['CommentWhereInput'][] | null; // [CommentWhereInput!]
    NOT?: NexusGenInputs['CommentWhereInput'][] | null; // [CommentWhereInput!]
    OR?: NexusGenInputs['CommentWhereInput'][] | null; // [CommentWhereInput!]
    body?: NexusGenInputs['StringFilter'] | null; // StringFilter
    createdAt?: NexusGenInputs['DateTimeFilter'] | null; // DateTimeFilter
    id?: NexusGenInputs['StringFilter'] | null; // StringFilter
    isDeleted?: NexusGenInputs['BoolFilter'] | null; // BoolFilter
    modifiedAt?: NexusGenInputs['DateTimeFilter'] | null; // DateTimeFilter
    submissionTrackFeedback?: NexusGenInputs['SubmissionTrackFeedbackListRelationFilter'] | null; // SubmissionTrackFeedbackListRelationFilter
    user?: NexusGenInputs['UserWhereInput'] | null; // UserWhereInput
    userId?: NexusGenInputs['StringFilter'] | null; // StringFilter
  }
  CommentWhereUniqueInput: { // input type
    id?: string | null; // String
  }
  CreateStackInput: { // input type
    commentBody: string; // String!
    description: string; // String!
    isPublic: boolean; // Boolean!
    name: string; // String!
    projectId: string; // String!
  }
  CreateSubmissionTrackFeedbackTemplateInput: { // input type
    alignmentRating: number; // Int!
    color?: string | null; // String
    commentBody: string; // String!
    description?: string | null; // String
    isDefault?: boolean | null; // Boolean
    label: string; // String!
    projectId: string; // String!
  }
  DateTimeFilter: { // input type
    equals?: NexusGenScalars['DateTime'] | null; // DateTime
    gt?: NexusGenScalars['DateTime'] | null; // DateTime
    gte?: NexusGenScalars['DateTime'] | null; // DateTime
    in?: NexusGenScalars['DateTime'][] | null; // [DateTime!]
    lt?: NexusGenScalars['DateTime'] | null; // DateTime
    lte?: NexusGenScalars['DateTime'] | null; // DateTime
    not?: NexusGenInputs['NestedDateTimeFilter'] | null; // NestedDateTimeFilter
    notIn?: NexusGenScalars['DateTime'][] | null; // [DateTime!]
  }
  DateTimeNullableFilter: { // input type
    equals?: NexusGenScalars['DateTime'] | null; // DateTime
    gt?: NexusGenScalars['DateTime'] | null; // DateTime
    gte?: NexusGenScalars['DateTime'] | null; // DateTime
    in?: NexusGenScalars['DateTime'][] | null; // [DateTime!]
    lt?: NexusGenScalars['DateTime'] | null; // DateTime
    lte?: NexusGenScalars['DateTime'] | null; // DateTime
    not?: NexusGenInputs['NestedDateTimeNullableFilter'] | null; // NestedDateTimeNullableFilter
    notIn?: NexusGenScalars['DateTime'][] | null; // [DateTime!]
  }
  DeclineSubmissionTrackInput: { // input type
    alignmentRating?: number | null; // Int
    commentBody?: string | null; // String
    submissionFeedbackTemplateId?: string | null; // String
    submissionTrackId: string; // String!
  }
  EnumSubmissionReviewStateFilter: { // input type
    equals?: NexusGenEnums['SubmissionReviewState'] | null; // SubmissionReviewState
    in?: NexusGenEnums['SubmissionReviewState'][] | null; // [SubmissionReviewState!]
    not?: NexusGenInputs['NestedEnumSubmissionReviewStateFilter'] | null; // NestedEnumSubmissionReviewStateFilter
    notIn?: NexusGenEnums['SubmissionReviewState'][] | null; // [SubmissionReviewState!]
  }
  EnumSubmissionTrackInteractionEventFilter: { // input type
    equals?: NexusGenEnums['SubmissionTrackInteractionEvent'] | null; // SubmissionTrackInteractionEvent
    in?: NexusGenEnums['SubmissionTrackInteractionEvent'][] | null; // [SubmissionTrackInteractionEvent!]
    not?: NexusGenInputs['NestedEnumSubmissionTrackInteractionEventFilter'] | null; // NestedEnumSubmissionTrackInteractionEventFilter
    notIn?: NexusGenEnums['SubmissionTrackInteractionEvent'][] | null; // [SubmissionTrackInteractionEvent!]
  }
  EnumSubmissionTrackReviewStateFilter: { // input type
    equals?: NexusGenEnums['SubmissionTrackReviewState'] | null; // SubmissionTrackReviewState
    in?: NexusGenEnums['SubmissionTrackReviewState'][] | null; // [SubmissionTrackReviewState!]
    not?: NexusGenInputs['NestedEnumSubmissionTrackReviewStateFilter'] | null; // NestedEnumSubmissionTrackReviewStateFilter
    notIn?: NexusGenEnums['SubmissionTrackReviewState'][] | null; // [SubmissionTrackReviewState!]
  }
  EnumTrackProcessingStateFilter: { // input type
    equals?: NexusGenEnums['TrackProcessingState'] | null; // TrackProcessingState
    in?: NexusGenEnums['TrackProcessingState'][] | null; // [TrackProcessingState!]
    not?: NexusGenInputs['NestedEnumTrackProcessingStateFilter'] | null; // NestedEnumTrackProcessingStateFilter
    notIn?: NexusGenEnums['TrackProcessingState'][] | null; // [TrackProcessingState!]
  }
  EnumUserRoleFilter: { // input type
    equals?: NexusGenEnums['UserRole'] | null; // UserRole
    in?: NexusGenEnums['UserRole'][] | null; // [UserRole!]
    not?: NexusGenInputs['NestedEnumUserRoleFilter'] | null; // NestedEnumUserRoleFilter
    notIn?: NexusGenEnums['UserRole'][] | null; // [UserRole!]
  }
  EnumUserTypeFilter: { // input type
    equals?: NexusGenEnums['UserType'] | null; // UserType
    in?: NexusGenEnums['UserType'][] | null; // [UserType!]
    not?: NexusGenInputs['NestedEnumUserTypeFilter'] | null; // NestedEnumUserTypeFilter
    notIn?: NexusGenEnums['UserType'][] | null; // [UserType!]
  }
  IntFilter: { // input type
    equals?: number | null; // Int
    gt?: number | null; // Int
    gte?: number | null; // Int
    in?: number[] | null; // [Int!]
    lt?: number | null; // Int
    lte?: number | null; // Int
    not?: NexusGenInputs['NestedIntFilter'] | null; // NestedIntFilter
    notIn?: number[] | null; // [Int!]
  }
  IntNullableFilter: { // input type
    equals?: number | null; // Int
    gt?: number | null; // Int
    gte?: number | null; // Int
    in?: number[] | null; // [Int!]
    lt?: number | null; // Int
    lte?: number | null; // Int
    not?: NexusGenInputs['NestedIntNullableFilter'] | null; // NestedIntNullableFilter
    notIn?: number[] | null; // [Int!]
  }
  NestedBoolFilter: { // input type
    equals?: boolean | null; // Boolean
    not?: NexusGenInputs['NestedBoolFilter'] | null; // NestedBoolFilter
  }
  NestedDateTimeFilter: { // input type
    equals?: NexusGenScalars['DateTime'] | null; // DateTime
    gt?: NexusGenScalars['DateTime'] | null; // DateTime
    gte?: NexusGenScalars['DateTime'] | null; // DateTime
    in?: NexusGenScalars['DateTime'][] | null; // [DateTime!]
    lt?: NexusGenScalars['DateTime'] | null; // DateTime
    lte?: NexusGenScalars['DateTime'] | null; // DateTime
    not?: NexusGenInputs['NestedDateTimeFilter'] | null; // NestedDateTimeFilter
    notIn?: NexusGenScalars['DateTime'][] | null; // [DateTime!]
  }
  NestedDateTimeNullableFilter: { // input type
    equals?: NexusGenScalars['DateTime'] | null; // DateTime
    gt?: NexusGenScalars['DateTime'] | null; // DateTime
    gte?: NexusGenScalars['DateTime'] | null; // DateTime
    in?: NexusGenScalars['DateTime'][] | null; // [DateTime!]
    lt?: NexusGenScalars['DateTime'] | null; // DateTime
    lte?: NexusGenScalars['DateTime'] | null; // DateTime
    not?: NexusGenInputs['NestedDateTimeNullableFilter'] | null; // NestedDateTimeNullableFilter
    notIn?: NexusGenScalars['DateTime'][] | null; // [DateTime!]
  }
  NestedEnumSubmissionReviewStateFilter: { // input type
    equals?: NexusGenEnums['SubmissionReviewState'] | null; // SubmissionReviewState
    in?: NexusGenEnums['SubmissionReviewState'][] | null; // [SubmissionReviewState!]
    not?: NexusGenInputs['NestedEnumSubmissionReviewStateFilter'] | null; // NestedEnumSubmissionReviewStateFilter
    notIn?: NexusGenEnums['SubmissionReviewState'][] | null; // [SubmissionReviewState!]
  }
  NestedEnumSubmissionTrackInteractionEventFilter: { // input type
    equals?: NexusGenEnums['SubmissionTrackInteractionEvent'] | null; // SubmissionTrackInteractionEvent
    in?: NexusGenEnums['SubmissionTrackInteractionEvent'][] | null; // [SubmissionTrackInteractionEvent!]
    not?: NexusGenInputs['NestedEnumSubmissionTrackInteractionEventFilter'] | null; // NestedEnumSubmissionTrackInteractionEventFilter
    notIn?: NexusGenEnums['SubmissionTrackInteractionEvent'][] | null; // [SubmissionTrackInteractionEvent!]
  }
  NestedEnumSubmissionTrackReviewStateFilter: { // input type
    equals?: NexusGenEnums['SubmissionTrackReviewState'] | null; // SubmissionTrackReviewState
    in?: NexusGenEnums['SubmissionTrackReviewState'][] | null; // [SubmissionTrackReviewState!]
    not?: NexusGenInputs['NestedEnumSubmissionTrackReviewStateFilter'] | null; // NestedEnumSubmissionTrackReviewStateFilter
    notIn?: NexusGenEnums['SubmissionTrackReviewState'][] | null; // [SubmissionTrackReviewState!]
  }
  NestedEnumTrackProcessingStateFilter: { // input type
    equals?: NexusGenEnums['TrackProcessingState'] | null; // TrackProcessingState
    in?: NexusGenEnums['TrackProcessingState'][] | null; // [TrackProcessingState!]
    not?: NexusGenInputs['NestedEnumTrackProcessingStateFilter'] | null; // NestedEnumTrackProcessingStateFilter
    notIn?: NexusGenEnums['TrackProcessingState'][] | null; // [TrackProcessingState!]
  }
  NestedEnumUserRoleFilter: { // input type
    equals?: NexusGenEnums['UserRole'] | null; // UserRole
    in?: NexusGenEnums['UserRole'][] | null; // [UserRole!]
    not?: NexusGenInputs['NestedEnumUserRoleFilter'] | null; // NestedEnumUserRoleFilter
    notIn?: NexusGenEnums['UserRole'][] | null; // [UserRole!]
  }
  NestedEnumUserTypeFilter: { // input type
    equals?: NexusGenEnums['UserType'] | null; // UserType
    in?: NexusGenEnums['UserType'][] | null; // [UserType!]
    not?: NexusGenInputs['NestedEnumUserTypeFilter'] | null; // NestedEnumUserTypeFilter
    notIn?: NexusGenEnums['UserType'][] | null; // [UserType!]
  }
  NestedIntFilter: { // input type
    equals?: number | null; // Int
    gt?: number | null; // Int
    gte?: number | null; // Int
    in?: number[] | null; // [Int!]
    lt?: number | null; // Int
    lte?: number | null; // Int
    not?: NexusGenInputs['NestedIntFilter'] | null; // NestedIntFilter
    notIn?: number[] | null; // [Int!]
  }
  NestedIntNullableFilter: { // input type
    equals?: number | null; // Int
    gt?: number | null; // Int
    gte?: number | null; // Int
    in?: number[] | null; // [Int!]
    lt?: number | null; // Int
    lte?: number | null; // Int
    not?: NexusGenInputs['NestedIntNullableFilter'] | null; // NestedIntNullableFilter
    notIn?: number[] | null; // [Int!]
  }
  NestedStringFilter: { // input type
    contains?: string | null; // String
    endsWith?: string | null; // String
    equals?: string | null; // String
    gt?: string | null; // String
    gte?: string | null; // String
    in?: string[] | null; // [String!]
    lt?: string | null; // String
    lte?: string | null; // String
    not?: NexusGenInputs['NestedStringFilter'] | null; // NestedStringFilter
    notIn?: string[] | null; // [String!]
    startsWith?: string | null; // String
  }
  NestedStringNullableFilter: { // input type
    contains?: string | null; // String
    endsWith?: string | null; // String
    equals?: string | null; // String
    gt?: string | null; // String
    gte?: string | null; // String
    in?: string[] | null; // [String!]
    lt?: string | null; // String
    lte?: string | null; // String
    not?: NexusGenInputs['NestedStringNullableFilter'] | null; // NestedStringNullableFilter
    notIn?: string[] | null; // [String!]
    startsWith?: string | null; // String
  }
  ProcessTrackUploadInput: { // input type
    trackIds: string; // String!
  }
  ProfileWhereInput: { // input type
    AND?: NexusGenInputs['ProfileWhereInput'][] | null; // [ProfileWhereInput!]
    NOT?: NexusGenInputs['ProfileWhereInput'][] | null; // [ProfileWhereInput!]
    OR?: NexusGenInputs['ProfileWhereInput'][] | null; // [ProfileWhereInput!]
    bio?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    city?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    country?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    id?: NexusGenInputs['IntFilter'] | null; // IntFilter
    previousLabels?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    user?: NexusGenInputs['UserWhereInput'] | null; // UserWhereInput
    userId?: NexusGenInputs['StringFilter'] | null; // StringFilter
  }
  ProjectListRelationFilter: { // input type
    every?: NexusGenInputs['ProjectWhereInput'] | null; // ProjectWhereInput
    none?: NexusGenInputs['ProjectWhereInput'] | null; // ProjectWhereInput
    some?: NexusGenInputs['ProjectWhereInput'] | null; // ProjectWhereInput
  }
  ProjectWhereInput: { // input type
    AND?: NexusGenInputs['ProjectWhereInput'][] | null; // [ProjectWhereInput!]
    NOT?: NexusGenInputs['ProjectWhereInput'][] | null; // [ProjectWhereInput!]
    OR?: NexusGenInputs['ProjectWhereInput'][] | null; // [ProjectWhereInput!]
    createdAt?: NexusGenInputs['DateTimeFilter'] | null; // DateTimeFilter
    feedbackTemplates?: NexusGenInputs['SubmissionTrackFeedbackTemplateListRelationFilter'] | null; // SubmissionTrackFeedbackTemplateListRelationFilter
    id?: NexusGenInputs['StringFilter'] | null; // StringFilter
    modifiedAt?: NexusGenInputs['DateTimeFilter'] | null; // DateTimeFilter
    name?: NexusGenInputs['StringFilter'] | null; // StringFilter
    slug?: NexusGenInputs['StringFilter'] | null; // StringFilter
    stacks?: NexusGenInputs['StackListRelationFilter'] | null; // StackListRelationFilter
    stripeCurrentPeriodEnd?: NexusGenInputs['DateTimeNullableFilter'] | null; // DateTimeNullableFilter
    stripeCustomerId?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    stripePriceId?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    stripeSubscriptionId?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    submissionTracks?: NexusGenInputs['SubmissionTrackListRelationFilter'] | null; // SubmissionTrackListRelationFilter
    submissions?: NexusGenInputs['SubmissionListRelationFilter'] | null; // SubmissionListRelationFilter
    users?: NexusGenInputs['UserListRelationFilter'] | null; // UserListRelationFilter
  }
  ProjectWhereUniqueInput: { // input type
    id?: string | null; // String
    slug?: string | null; // String
    stripeCustomerId?: string | null; // String
    stripeSubscriptionId?: string | null; // String
  }
  SendSubmissionInput: { // input type
    optionalMessage?: string | null; // String
    projectId: string; // String!
    title: string; // String!
    trackIds: string[]; // [String!]!
    trackKeys: string[]; // [String!]!
    userId: string; // String!
  }
  ShortlistSubmissionTrackInput: { // input type
    stackId: string; // String!
    submissionTrackId: string; // String!
  }
  StackListRelationFilter: { // input type
    every?: NexusGenInputs['StackWhereInput'] | null; // StackWhereInput
    none?: NexusGenInputs['StackWhereInput'] | null; // StackWhereInput
    some?: NexusGenInputs['StackWhereInput'] | null; // StackWhereInput
  }
  StackWhereInput: { // input type
    AND?: NexusGenInputs['StackWhereInput'][] | null; // [StackWhereInput!]
    NOT?: NexusGenInputs['StackWhereInput'][] | null; // [StackWhereInput!]
    OR?: NexusGenInputs['StackWhereInput'][] | null; // [StackWhereInput!]
    commentBody?: NexusGenInputs['StringFilter'] | null; // StringFilter
    createdAt?: NexusGenInputs['DateTimeFilter'] | null; // DateTimeFilter
    description?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    id?: NexusGenInputs['StringFilter'] | null; // StringFilter
    isPublic?: NexusGenInputs['BoolFilter'] | null; // BoolFilter
    modifiedAt?: NexusGenInputs['DateTimeFilter'] | null; // DateTimeFilter
    name?: NexusGenInputs['StringFilter'] | null; // StringFilter
    project?: NexusGenInputs['ProjectWhereInput'] | null; // ProjectWhereInput
    projectId?: NexusGenInputs['StringFilter'] | null; // StringFilter
    submissionTracks?: NexusGenInputs['SubmissionTrackListRelationFilter'] | null; // SubmissionTrackListRelationFilter
  }
  StackWhereUniqueInput: { // input type
    id?: string | null; // String
  }
  StartTrackUploadInput: { // input type
    displayTitle: string; // String!
    filename: string; // String!
    format: string; // String!
    size: number; // Int!
    userId: string; // String!
  }
  StringFilter: { // input type
    contains?: string | null; // String
    endsWith?: string | null; // String
    equals?: string | null; // String
    gt?: string | null; // String
    gte?: string | null; // String
    in?: string[] | null; // [String!]
    lt?: string | null; // String
    lte?: string | null; // String
    mode?: NexusGenEnums['QueryMode'] | null; // QueryMode
    not?: NexusGenInputs['NestedStringFilter'] | null; // NestedStringFilter
    notIn?: string[] | null; // [String!]
    startsWith?: string | null; // String
  }
  StringNullableFilter: { // input type
    contains?: string | null; // String
    endsWith?: string | null; // String
    equals?: string | null; // String
    gt?: string | null; // String
    gte?: string | null; // String
    in?: string[] | null; // [String!]
    lt?: string | null; // String
    lte?: string | null; // String
    mode?: NexusGenEnums['QueryMode'] | null; // QueryMode
    not?: NexusGenInputs['NestedStringNullableFilter'] | null; // NestedStringNullableFilter
    notIn?: string[] | null; // [String!]
    startsWith?: string | null; // String
  }
  SubmissionListRelationFilter: { // input type
    every?: NexusGenInputs['SubmissionWhereInput'] | null; // SubmissionWhereInput
    none?: NexusGenInputs['SubmissionWhereInput'] | null; // SubmissionWhereInput
    some?: NexusGenInputs['SubmissionWhereInput'] | null; // SubmissionWhereInput
  }
  SubmissionOrderByInput: { // input type
    createdAt?: NexusGenEnums['SortOrder'] | null; // SortOrder
    id?: NexusGenEnums['SortOrder'] | null; // SortOrder
    modifiedAt?: NexusGenEnums['SortOrder'] | null; // SortOrder
    optionalMessage?: NexusGenEnums['SortOrder'] | null; // SortOrder
    projectId?: NexusGenEnums['SortOrder'] | null; // SortOrder
    reviewCompletedAt?: NexusGenEnums['SortOrder'] | null; // SortOrder
    reviewState?: NexusGenEnums['SortOrder'] | null; // SortOrder
    title?: NexusGenEnums['SortOrder'] | null; // SortOrder
    userId?: NexusGenEnums['SortOrder'] | null; // SortOrder
  }
  SubmissionTrackFeedbackListRelationFilter: { // input type
    every?: NexusGenInputs['SubmissionTrackFeedbackWhereInput'] | null; // SubmissionTrackFeedbackWhereInput
    none?: NexusGenInputs['SubmissionTrackFeedbackWhereInput'] | null; // SubmissionTrackFeedbackWhereInput
    some?: NexusGenInputs['SubmissionTrackFeedbackWhereInput'] | null; // SubmissionTrackFeedbackWhereInput
  }
  SubmissionTrackFeedbackTemplateListRelationFilter: { // input type
    every?: NexusGenInputs['SubmissionTrackFeedbackTemplateWhereInput'] | null; // SubmissionTrackFeedbackTemplateWhereInput
    none?: NexusGenInputs['SubmissionTrackFeedbackTemplateWhereInput'] | null; // SubmissionTrackFeedbackTemplateWhereInput
    some?: NexusGenInputs['SubmissionTrackFeedbackTemplateWhereInput'] | null; // SubmissionTrackFeedbackTemplateWhereInput
  }
  SubmissionTrackFeedbackTemplateWhereInput: { // input type
    AND?: NexusGenInputs['SubmissionTrackFeedbackTemplateWhereInput'][] | null; // [SubmissionTrackFeedbackTemplateWhereInput!]
    NOT?: NexusGenInputs['SubmissionTrackFeedbackTemplateWhereInput'][] | null; // [SubmissionTrackFeedbackTemplateWhereInput!]
    OR?: NexusGenInputs['SubmissionTrackFeedbackTemplateWhereInput'][] | null; // [SubmissionTrackFeedbackTemplateWhereInput!]
    alignmentRating?: NexusGenInputs['IntNullableFilter'] | null; // IntNullableFilter
    color?: NexusGenInputs['StringFilter'] | null; // StringFilter
    commentBody?: NexusGenInputs['StringFilter'] | null; // StringFilter
    createdAt?: NexusGenInputs['DateTimeFilter'] | null; // DateTimeFilter
    description?: NexusGenInputs['StringFilter'] | null; // StringFilter
    id?: NexusGenInputs['StringFilter'] | null; // StringFilter
    isDefault?: NexusGenInputs['BoolFilter'] | null; // BoolFilter
    label?: NexusGenInputs['StringFilter'] | null; // StringFilter
    modifiedAt?: NexusGenInputs['DateTimeFilter'] | null; // DateTimeFilter
    project?: NexusGenInputs['ProjectWhereInput'] | null; // ProjectWhereInput
    projectId?: NexusGenInputs['StringFilter'] | null; // StringFilter
  }
  SubmissionTrackFeedbackTemplateWhereUniqueInput: { // input type
    id?: string | null; // String
  }
  SubmissionTrackFeedbackWhereInput: { // input type
    AND?: NexusGenInputs['SubmissionTrackFeedbackWhereInput'][] | null; // [SubmissionTrackFeedbackWhereInput!]
    NOT?: NexusGenInputs['SubmissionTrackFeedbackWhereInput'][] | null; // [SubmissionTrackFeedbackWhereInput!]
    OR?: NexusGenInputs['SubmissionTrackFeedbackWhereInput'][] | null; // [SubmissionTrackFeedbackWhereInput!]
    alignmentRating?: NexusGenInputs['IntNullableFilter'] | null; // IntNullableFilter
    comments?: NexusGenInputs['CommentListRelationFilter'] | null; // CommentListRelationFilter
    createdAt?: NexusGenInputs['DateTimeFilter'] | null; // DateTimeFilter
    id?: NexusGenInputs['StringFilter'] | null; // StringFilter
    modifiedAt?: NexusGenInputs['DateTimeFilter'] | null; // DateTimeFilter
    submissionTrack?: NexusGenInputs['SubmissionTrackListRelationFilter'] | null; // SubmissionTrackListRelationFilter
  }
  SubmissionTrackInteractionInput: { // input type
    playEnd?: number | null; // Int
    playStart?: number | null; // Int
    submissionTrackId: string; // String!
    type: string; // String!
  }
  SubmissionTrackInteractionListRelationFilter: { // input type
    every?: NexusGenInputs['SubmissionTrackInteractionWhereInput'] | null; // SubmissionTrackInteractionWhereInput
    none?: NexusGenInputs['SubmissionTrackInteractionWhereInput'] | null; // SubmissionTrackInteractionWhereInput
    some?: NexusGenInputs['SubmissionTrackInteractionWhereInput'] | null; // SubmissionTrackInteractionWhereInput
  }
  SubmissionTrackInteractionWhereInput: { // input type
    AND?: NexusGenInputs['SubmissionTrackInteractionWhereInput'][] | null; // [SubmissionTrackInteractionWhereInput!]
    NOT?: NexusGenInputs['SubmissionTrackInteractionWhereInput'][] | null; // [SubmissionTrackInteractionWhereInput!]
    OR?: NexusGenInputs['SubmissionTrackInteractionWhereInput'][] | null; // [SubmissionTrackInteractionWhereInput!]
    city?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    country?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    countryCode?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    createdAt?: NexusGenInputs['DateTimeFilter'] | null; // DateTimeFilter
    id?: NexusGenInputs['StringFilter'] | null; // StringFilter
    locationIp?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    playEnd?: NexusGenInputs['IntNullableFilter'] | null; // IntNullableFilter
    playStart?: NexusGenInputs['IntNullableFilter'] | null; // IntNullableFilter
    submissionTrack?: NexusGenInputs['SubmissionTrackWhereInput'] | null; // SubmissionTrackWhereInput
    submissionTrackId?: NexusGenInputs['StringFilter'] | null; // StringFilter
    type?: NexusGenInputs['EnumSubmissionTrackInteractionEventFilter'] | null; // EnumSubmissionTrackInteractionEventFilter
  }
  SubmissionTrackInteractionWhereUniqueInput: { // input type
    id?: string | null; // String
  }
  SubmissionTrackListRelationFilter: { // input type
    every?: NexusGenInputs['SubmissionTrackWhereInput'] | null; // SubmissionTrackWhereInput
    none?: NexusGenInputs['SubmissionTrackWhereInput'] | null; // SubmissionTrackWhereInput
    some?: NexusGenInputs['SubmissionTrackWhereInput'] | null; // SubmissionTrackWhereInput
  }
  SubmissionTrackOrderByInput: { // input type
    createdAt?: NexusGenEnums['SortOrder'] | null; // SortOrder
    id?: NexusGenEnums['SortOrder'] | null; // SortOrder
    modifiedAt?: NexusGenEnums['SortOrder'] | null; // SortOrder
    projectId?: NexusGenEnums['SortOrder'] | null; // SortOrder
    reviewState?: NexusGenEnums['SortOrder'] | null; // SortOrder
    stackId?: NexusGenEnums['SortOrder'] | null; // SortOrder
    submissionId?: NexusGenEnums['SortOrder'] | null; // SortOrder
    submissionTrackFeedbackId?: NexusGenEnums['SortOrder'] | null; // SortOrder
    trackId?: NexusGenEnums['SortOrder'] | null; // SortOrder
  }
  SubmissionTrackWhereInput: { // input type
    AND?: NexusGenInputs['SubmissionTrackWhereInput'][] | null; // [SubmissionTrackWhereInput!]
    NOT?: NexusGenInputs['SubmissionTrackWhereInput'][] | null; // [SubmissionTrackWhereInput!]
    OR?: NexusGenInputs['SubmissionTrackWhereInput'][] | null; // [SubmissionTrackWhereInput!]
    createdAt?: NexusGenInputs['DateTimeFilter'] | null; // DateTimeFilter
    feedback?: NexusGenInputs['SubmissionTrackFeedbackWhereInput'] | null; // SubmissionTrackFeedbackWhereInput
    id?: NexusGenInputs['StringFilter'] | null; // StringFilter
    modifiedAt?: NexusGenInputs['DateTimeFilter'] | null; // DateTimeFilter
    project?: NexusGenInputs['ProjectWhereInput'] | null; // ProjectWhereInput
    projectId?: NexusGenInputs['StringFilter'] | null; // StringFilter
    reviewState?: NexusGenInputs['EnumSubmissionTrackReviewStateFilter'] | null; // EnumSubmissionTrackReviewStateFilter
    stack?: NexusGenInputs['StackWhereInput'] | null; // StackWhereInput
    stackId?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    submission?: NexusGenInputs['SubmissionWhereInput'] | null; // SubmissionWhereInput
    submissionId?: NexusGenInputs['StringFilter'] | null; // StringFilter
    submissionTrackFeedbackId?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    submissionTrackInteractions?: NexusGenInputs['SubmissionTrackInteractionListRelationFilter'] | null; // SubmissionTrackInteractionListRelationFilter
    track?: NexusGenInputs['TrackWhereInput'] | null; // TrackWhereInput
    trackId?: NexusGenInputs['StringFilter'] | null; // StringFilter
  }
  SubmissionTrackWhereUniqueInput: { // input type
    id?: string | null; // String
  }
  SubmissionWhereInput: { // input type
    AND?: NexusGenInputs['SubmissionWhereInput'][] | null; // [SubmissionWhereInput!]
    NOT?: NexusGenInputs['SubmissionWhereInput'][] | null; // [SubmissionWhereInput!]
    OR?: NexusGenInputs['SubmissionWhereInput'][] | null; // [SubmissionWhereInput!]
    createdAt?: NexusGenInputs['DateTimeFilter'] | null; // DateTimeFilter
    id?: NexusGenInputs['StringFilter'] | null; // StringFilter
    modifiedAt?: NexusGenInputs['DateTimeFilter'] | null; // DateTimeFilter
    optionalMessage?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    project?: NexusGenInputs['ProjectWhereInput'] | null; // ProjectWhereInput
    projectId?: NexusGenInputs['StringFilter'] | null; // StringFilter
    reviewCompletedAt?: NexusGenInputs['DateTimeNullableFilter'] | null; // DateTimeNullableFilter
    reviewState?: NexusGenInputs['EnumSubmissionReviewStateFilter'] | null; // EnumSubmissionReviewStateFilter
    submissionTracks?: NexusGenInputs['SubmissionTrackListRelationFilter'] | null; // SubmissionTrackListRelationFilter
    title?: NexusGenInputs['StringFilter'] | null; // StringFilter
    user?: NexusGenInputs['UserWhereInput'] | null; // UserWhereInput
    userId?: NexusGenInputs['StringFilter'] | null; // StringFilter
  }
  SubmissionWhereUniqueInput: { // input type
    id?: string | null; // String
  }
  TrackListRelationFilter: { // input type
    every?: NexusGenInputs['TrackWhereInput'] | null; // TrackWhereInput
    none?: NexusGenInputs['TrackWhereInput'] | null; // TrackWhereInput
    some?: NexusGenInputs['TrackWhereInput'] | null; // TrackWhereInput
  }
  TrackWhereInput: { // input type
    AND?: NexusGenInputs['TrackWhereInput'][] | null; // [TrackWhereInput!]
    NOT?: NexusGenInputs['TrackWhereInput'][] | null; // [TrackWhereInput!]
    OR?: NexusGenInputs['TrackWhereInput'][] | null; // [TrackWhereInput!]
    SubmissionTrack?: NexusGenInputs['SubmissionTrackListRelationFilter'] | null; // SubmissionTrackListRelationFilter
    createdAt?: NexusGenInputs['DateTimeFilter'] | null; // DateTimeFilter
    displayTitle?: NexusGenInputs['StringFilter'] | null; // StringFilter
    duration?: NexusGenInputs['IntNullableFilter'] | null; // IntNullableFilter
    filename?: NexusGenInputs['StringFilter'] | null; // StringFilter
    format?: NexusGenInputs['StringFilter'] | null; // StringFilter
    id?: NexusGenInputs['StringFilter'] | null; // StringFilter
    isDeleted?: NexusGenInputs['BoolFilter'] | null; // BoolFilter
    license?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    modifiedAt?: NexusGenInputs['DateTimeFilter'] | null; // DateTimeFilter
    size?: NexusGenInputs['IntFilter'] | null; // IntFilter
    state?: NexusGenInputs['EnumTrackProcessingStateFilter'] | null; // EnumTrackProcessingStateFilter
    trackKey?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    user?: NexusGenInputs['UserWhereInput'] | null; // UserWhereInput
    userId?: NexusGenInputs['StringFilter'] | null; // StringFilter
    waveformId?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    waveformKey?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
  }
  UpdateStackInput: { // input type
    commentBody?: string | null; // String
    description?: string | null; // String
    isPublic?: boolean | null; // Boolean
    name?: string | null; // String
  }
  UpdateSubmissionTrackFeedbackTemplateInput: { // input type
    alignmentRating?: number | null; // Int
    color?: string | null; // String
    commentBody?: string | null; // String
    description?: string | null; // String
    isDefault?: boolean | null; // Boolean
    isPublic?: boolean | null; // Boolean
    label?: string | null; // String
  }
  UpdateTrackInput: { // input type
    displayTitle?: string | null; // String
    duration?: number | null; // Int
    isDeleted?: boolean | null; // Boolean
    state?: string | null; // String
    trackKey?: string | null; // String
    waveformId?: string | null; // String
    waveformKey?: string | null; // String
  }
  UpdateUserInput: { // input type
    email?: string | null; // String
    name?: string | null; // String
    userId: string; // String!
    username?: string | null; // String
  }
  UpsertUserInput: { // input type
    email: string; // String!
    name?: string | null; // String
    username?: string | null; // String
  }
  UserListRelationFilter: { // input type
    every?: NexusGenInputs['UserWhereInput'] | null; // UserWhereInput
    none?: NexusGenInputs['UserWhereInput'] | null; // UserWhereInput
    some?: NexusGenInputs['UserWhereInput'] | null; // UserWhereInput
  }
  UserWhereInput: { // input type
    AND?: NexusGenInputs['UserWhereInput'][] | null; // [UserWhereInput!]
    NOT?: NexusGenInputs['UserWhereInput'][] | null; // [UserWhereInput!]
    OR?: NexusGenInputs['UserWhereInput'][] | null; // [UserWhereInput!]
    comments?: NexusGenInputs['CommentListRelationFilter'] | null; // CommentListRelationFilter
    createdAt?: NexusGenInputs['DateTimeFilter'] | null; // DateTimeFilter
    email?: NexusGenInputs['StringFilter'] | null; // StringFilter
    id?: NexusGenInputs['StringFilter'] | null; // StringFilter
    isGuest?: NexusGenInputs['BoolFilter'] | null; // BoolFilter
    modifiedAt?: NexusGenInputs['DateTimeFilter'] | null; // DateTimeFilter
    name?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    profile?: NexusGenInputs['ProfileWhereInput'] | null; // ProfileWhereInput
    projects?: NexusGenInputs['ProjectListRelationFilter'] | null; // ProjectListRelationFilter
    role?: NexusGenInputs['EnumUserRoleFilter'] | null; // EnumUserRoleFilter
    stackAttributionId?: NexusGenInputs['IntNullableFilter'] | null; // IntNullableFilter
    submissions?: NexusGenInputs['SubmissionListRelationFilter'] | null; // SubmissionListRelationFilter
    tracks?: NexusGenInputs['TrackListRelationFilter'] | null; // TrackListRelationFilter
    type?: NexusGenInputs['EnumUserTypeFilter'] | null; // EnumUserTypeFilter
    username?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
  }
  UserWhereUniqueInput: { // input type
    email?: string | null; // String
    id?: string | null; // String
    username?: string | null; // String
  }
}

export interface NexusGenEnums {
  PaidPlan: "pro"
  QueryMode: "default" | "insensitive"
  SortOrder: "asc" | "desc"
  SubmissionReviewState: "COMPLETE" | "PENDING"
  SubmissionTrackInteractionEvent: "DOWNLOAD" | "PLAY_END" | "PLAY_START"
  SubmissionTrackReviewState: "DECLINED" | "PENDING" | "SHORTLISTED"
  TrackProcessingState: "COMPLETED" | "FAILED" | "PENDING"
  UserRole: "ADMIN" | "USER"
  UserType: "ARTIST" | "BUSINESS"
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
  DateTime: any
}

export interface NexusGenObjects {
  Comment: { // root type
    body: string; // String!
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    id: string; // String!
    isDeleted: boolean; // Boolean!
    modifiedAt: NexusGenScalars['DateTime']; // DateTime!
  }
  DeleteTrackByKeyResponse: { // root type
    error?: string | null; // String
    success: boolean; // Boolean!
  }
  Mutation: {};
  ProcessTrackUploadsResponse: { // root type
    success: boolean; // Boolean!
  }
  Profile: { // root type
    bio?: string | null; // String
    city?: string | null; // String
    country?: string | null; // String
    id: number; // Int!
    previousLabels?: string | null; // String
  }
  Project: { // root type
    id: string; // String!
    name: string; // String!
    slug: string; // String!
  }
  Query: {};
  Stack: { // root type
    commentBody: string; // String!
    description?: string | null; // String
    id: string; // String!
    isPublic: boolean; // Boolean!
    name: string; // String!
  }
  StartTrackUploadResponse: { // root type
    presignedPostData: string; // String!
    trackId: string; // String!
    trackKey: string; // String!
  }
  Submission: { // root type
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    id: string; // String!
    optionalMessage?: string | null; // String
    reviewCompletedAt?: NexusGenScalars['DateTime'] | null; // DateTime
    reviewState: NexusGenEnums['SubmissionReviewState']; // SubmissionReviewState!
    title: string; // String!
  }
  SubmissionTrack: { // root type
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    id: string; // String!
    modifiedAt: NexusGenScalars['DateTime']; // DateTime!
    reviewState: NexusGenEnums['SubmissionTrackReviewState']; // SubmissionTrackReviewState!
    submissionId: string; // String!
  }
  SubmissionTrackFeedback: { // root type
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    id: string; // String!
    modifiedAt: NexusGenScalars['DateTime']; // DateTime!
  }
  SubmissionTrackFeedbackTemplate: { // root type
    alignmentRating?: number | null; // Int
    color: string; // String!
    commentBody: string; // String!
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    description: string; // String!
    id: string; // String!
    isDefault: boolean; // Boolean!
    label: string; // String!
    modifiedAt: NexusGenScalars['DateTime']; // DateTime!
  }
  SubmissionTrackInteraction: { // root type
    city?: string | null; // String
    country?: string | null; // String
    countryCode?: string | null; // String
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    id: string; // String!
    locationIp?: string | null; // String
    playEnd?: number | null; // Int
    playStart?: number | null; // Int
    type: NexusGenEnums['SubmissionTrackInteractionEvent']; // SubmissionTrackInteractionEvent!
  }
  Track: { // root type
    displayTitle: string; // String!
    duration?: number | null; // Int
    format: string; // String!
    id: string; // String!
    isDeleted: boolean; // Boolean!
    license?: string | null; // String
    size: number; // Int!
    state: NexusGenEnums['TrackProcessingState']; // TrackProcessingState!
    trackKey?: string | null; // String
    waveformId?: string | null; // String
    waveformKey?: string | null; // String
  }
  User: { // root type
    email: string; // String!
    id: string; // String!
    isGuest: boolean; // Boolean!
    name?: string | null; // String
    role: NexusGenEnums['UserRole']; // UserRole!
    type: NexusGenEnums['UserType']; // UserType!
    username?: string | null; // String
  }
}

export interface NexusGenInterfaces {
}

export interface NexusGenUnions {
}

export type NexusGenRootTypes = NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars & NexusGenEnums

export interface NexusGenFieldTypes {
  Comment: { // field return type
    body: string; // String!
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    id: string; // String!
    isDeleted: boolean; // Boolean!
    modifiedAt: NexusGenScalars['DateTime']; // DateTime!
    user: NexusGenRootTypes['User']; // User!
  }
  DeleteTrackByKeyResponse: { // field return type
    error: string | null; // String
    success: boolean; // Boolean!
  }
  Mutation: { // field return type
    createFeedbackTemplate: NexusGenRootTypes['SubmissionTrackFeedbackTemplate'] | null; // SubmissionTrackFeedbackTemplate
    createGuestUser: NexusGenRootTypes['User'] | null; // User
    createProject: NexusGenRootTypes['Project'] | null; // Project
    createStack: NexusGenRootTypes['Stack'] | null; // Stack
    createStripeCheckoutBillingPortalUrl: string | null; // String
    createStripeCheckoutSession: string | null; // String
    createSubmissionTrackInteraction: NexusGenRootTypes['SubmissionTrackInteraction'] | null; // SubmissionTrackInteraction
    declineSubmissionTrack: NexusGenRootTypes['SubmissionTrack'] | null; // SubmissionTrack
    deleteTrackByKey: NexusGenRootTypes['DeleteTrackByKeyResponse'] | null; // DeleteTrackByKeyResponse
    inviteToProject: boolean | null; // Boolean
    moveSubmissionTrack: NexusGenRootTypes['SubmissionTrack'] | null; // SubmissionTrack
    processTrackUploads: NexusGenRootTypes['ProcessTrackUploadsResponse'] | null; // ProcessTrackUploadsResponse
    removeUserFromProject: NexusGenRootTypes['Project'] | null; // Project
    sendSubmission: NexusGenRootTypes['Submission'] | null; // Submission
    shortlistSubmissionTrack: NexusGenRootTypes['SubmissionTrack'] | null; // SubmissionTrack
    startTrackUpload: NexusGenRootTypes['StartTrackUploadResponse'] | null; // StartTrackUploadResponse
    updateAsBusinessUser: NexusGenRootTypes['User'] | null; // User
    updateFeedbackTemplate: NexusGenRootTypes['SubmissionTrackFeedbackTemplate'] | null; // SubmissionTrackFeedbackTemplate
    updateFeedbackTemplateAsDefault: NexusGenRootTypes['SubmissionTrackFeedbackTemplate'] | null; // SubmissionTrackFeedbackTemplate
    updateStack: NexusGenRootTypes['Stack'] | null; // Stack
    updateTrack: NexusGenRootTypes['Track'] | null; // Track
    updateUser: NexusGenRootTypes['User'] | null; // User
    upsertUser: NexusGenRootTypes['User'] | null; // User
  }
  ProcessTrackUploadsResponse: { // field return type
    success: boolean; // Boolean!
  }
  Profile: { // field return type
    bio: string | null; // String
    city: string | null; // String
    country: string | null; // String
    id: number; // Int!
    previousLabels: string | null; // String
    user: NexusGenRootTypes['User']; // User!
  }
  Project: { // field return type
    feedbackTemplates: NexusGenRootTypes['SubmissionTrackFeedbackTemplate'][]; // [SubmissionTrackFeedbackTemplate!]!
    id: string; // String!
    name: string; // String!
    paidPlan: NexusGenEnums['PaidPlan'] | null; // PaidPlan
    slug: string; // String!
    stacks: NexusGenRootTypes['Stack'][]; // [Stack!]!
    submissionTracks: NexusGenRootTypes['SubmissionTrack'][]; // [SubmissionTrack!]!
    submissions: NexusGenRootTypes['Submission'][]; // [Submission!]!
    users: NexusGenRootTypes['User'][]; // [User!]!
  }
  Query: { // field return type
    currentUser: NexusGenRootTypes['User'] | null; // User
    project: NexusGenRootTypes['Project'] | null; // Project
    stack: NexusGenRootTypes['Stack'] | null; // Stack
    submission: NexusGenRootTypes['Submission'] | null; // Submission
    submissionTrack: NexusGenRootTypes['SubmissionTrack'] | null; // SubmissionTrack
    track: NexusGenRootTypes['User'] | null; // User
    userBySlug: NexusGenRootTypes['User'] | null; // User
  }
  Stack: { // field return type
    commentBody: string; // String!
    description: string | null; // String
    id: string; // String!
    isPublic: boolean; // Boolean!
    name: string; // String!
    project: NexusGenRootTypes['Project']; // Project!
    submissionTracks: NexusGenRootTypes['SubmissionTrack'][]; // [SubmissionTrack!]!
  }
  StartTrackUploadResponse: { // field return type
    presignedPostData: string; // String!
    trackId: string; // String!
    trackKey: string; // String!
  }
  Submission: { // field return type
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    id: string; // String!
    optionalMessage: string | null; // String
    project: NexusGenRootTypes['Project']; // Project!
    reviewCompletedAt: NexusGenScalars['DateTime'] | null; // DateTime
    reviewState: NexusGenEnums['SubmissionReviewState']; // SubmissionReviewState!
    submissionTracks: NexusGenRootTypes['SubmissionTrack'][]; // [SubmissionTrack!]!
    title: string; // String!
    user: NexusGenRootTypes['User']; // User!
  }
  SubmissionTrack: { // field return type
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    feedback: NexusGenRootTypes['SubmissionTrackFeedback'] | null; // SubmissionTrackFeedback
    id: string; // String!
    modifiedAt: NexusGenScalars['DateTime']; // DateTime!
    project: NexusGenRootTypes['Project']; // Project!
    reviewState: NexusGenEnums['SubmissionTrackReviewState']; // SubmissionTrackReviewState!
    stack: NexusGenRootTypes['Stack'] | null; // Stack
    submission: NexusGenRootTypes['Submission']; // Submission!
    submissionId: string; // String!
    submissionTrackInteractions: NexusGenRootTypes['SubmissionTrackInteraction'][]; // [SubmissionTrackInteraction!]!
    track: NexusGenRootTypes['Track']; // Track!
  }
  SubmissionTrackFeedback: { // field return type
    comments: NexusGenRootTypes['Comment'][]; // [Comment!]!
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    id: string; // String!
    modifiedAt: NexusGenScalars['DateTime']; // DateTime!
    submissionTrack: NexusGenRootTypes['SubmissionTrack'][]; // [SubmissionTrack!]!
  }
  SubmissionTrackFeedbackTemplate: { // field return type
    alignmentRating: number | null; // Int
    color: string; // String!
    commentBody: string; // String!
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    description: string; // String!
    id: string; // String!
    isDefault: boolean; // Boolean!
    label: string; // String!
    modifiedAt: NexusGenScalars['DateTime']; // DateTime!
    project: NexusGenRootTypes['Project']; // Project!
  }
  SubmissionTrackInteraction: { // field return type
    city: string | null; // String
    country: string | null; // String
    countryCode: string | null; // String
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    id: string; // String!
    locationIp: string | null; // String
    playEnd: number | null; // Int
    playStart: number | null; // Int
    submissionTrack: NexusGenRootTypes['SubmissionTrack']; // SubmissionTrack!
    type: NexusGenEnums['SubmissionTrackInteractionEvent']; // SubmissionTrackInteractionEvent!
  }
  Track: { // field return type
    displayTitle: string; // String!
    downloadUrl: string | null; // String
    duration: number | null; // Int
    format: string; // String!
    id: string; // String!
    isDeleted: boolean; // Boolean!
    license: string | null; // String
    size: number; // Int!
    state: NexusGenEnums['TrackProcessingState']; // TrackProcessingState!
    streamUrl: string | null; // String
    trackKey: string | null; // String
    user: NexusGenRootTypes['User']; // User!
    waveformData: string | null; // String
    waveformId: string | null; // String
    waveformKey: string | null; // String
    waveformUrl: string | null; // String
  }
  User: { // field return type
    email: string; // String!
    id: string; // String!
    isGuest: boolean; // Boolean!
    name: string | null; // String
    profile: NexusGenRootTypes['Profile'] | null; // Profile
    projects: NexusGenRootTypes['Project'][]; // [Project!]!
    role: NexusGenEnums['UserRole']; // UserRole!
    type: NexusGenEnums['UserType']; // UserType!
    username: string | null; // String
  }
}

export interface NexusGenFieldTypeNames {
  Comment: { // field return type name
    body: 'String'
    createdAt: 'DateTime'
    id: 'String'
    isDeleted: 'Boolean'
    modifiedAt: 'DateTime'
    user: 'User'
  }
  DeleteTrackByKeyResponse: { // field return type name
    error: 'String'
    success: 'Boolean'
  }
  Mutation: { // field return type name
    createFeedbackTemplate: 'SubmissionTrackFeedbackTemplate'
    createGuestUser: 'User'
    createProject: 'Project'
    createStack: 'Stack'
    createStripeCheckoutBillingPortalUrl: 'String'
    createStripeCheckoutSession: 'String'
    createSubmissionTrackInteraction: 'SubmissionTrackInteraction'
    declineSubmissionTrack: 'SubmissionTrack'
    deleteTrackByKey: 'DeleteTrackByKeyResponse'
    inviteToProject: 'Boolean'
    moveSubmissionTrack: 'SubmissionTrack'
    processTrackUploads: 'ProcessTrackUploadsResponse'
    removeUserFromProject: 'Project'
    sendSubmission: 'Submission'
    shortlistSubmissionTrack: 'SubmissionTrack'
    startTrackUpload: 'StartTrackUploadResponse'
    updateAsBusinessUser: 'User'
    updateFeedbackTemplate: 'SubmissionTrackFeedbackTemplate'
    updateFeedbackTemplateAsDefault: 'SubmissionTrackFeedbackTemplate'
    updateStack: 'Stack'
    updateTrack: 'Track'
    updateUser: 'User'
    upsertUser: 'User'
  }
  ProcessTrackUploadsResponse: { // field return type name
    success: 'Boolean'
  }
  Profile: { // field return type name
    bio: 'String'
    city: 'String'
    country: 'String'
    id: 'Int'
    previousLabels: 'String'
    user: 'User'
  }
  Project: { // field return type name
    feedbackTemplates: 'SubmissionTrackFeedbackTemplate'
    id: 'String'
    name: 'String'
    paidPlan: 'PaidPlan'
    slug: 'String'
    stacks: 'Stack'
    submissionTracks: 'SubmissionTrack'
    submissions: 'Submission'
    users: 'User'
  }
  Query: { // field return type name
    currentUser: 'User'
    project: 'Project'
    stack: 'Stack'
    submission: 'Submission'
    submissionTrack: 'SubmissionTrack'
    track: 'User'
    userBySlug: 'User'
  }
  Stack: { // field return type name
    commentBody: 'String'
    description: 'String'
    id: 'String'
    isPublic: 'Boolean'
    name: 'String'
    project: 'Project'
    submissionTracks: 'SubmissionTrack'
  }
  StartTrackUploadResponse: { // field return type name
    presignedPostData: 'String'
    trackId: 'String'
    trackKey: 'String'
  }
  Submission: { // field return type name
    createdAt: 'DateTime'
    id: 'String'
    optionalMessage: 'String'
    project: 'Project'
    reviewCompletedAt: 'DateTime'
    reviewState: 'SubmissionReviewState'
    submissionTracks: 'SubmissionTrack'
    title: 'String'
    user: 'User'
  }
  SubmissionTrack: { // field return type name
    createdAt: 'DateTime'
    feedback: 'SubmissionTrackFeedback'
    id: 'String'
    modifiedAt: 'DateTime'
    project: 'Project'
    reviewState: 'SubmissionTrackReviewState'
    stack: 'Stack'
    submission: 'Submission'
    submissionId: 'String'
    submissionTrackInteractions: 'SubmissionTrackInteraction'
    track: 'Track'
  }
  SubmissionTrackFeedback: { // field return type name
    comments: 'Comment'
    createdAt: 'DateTime'
    id: 'String'
    modifiedAt: 'DateTime'
    submissionTrack: 'SubmissionTrack'
  }
  SubmissionTrackFeedbackTemplate: { // field return type name
    alignmentRating: 'Int'
    color: 'String'
    commentBody: 'String'
    createdAt: 'DateTime'
    description: 'String'
    id: 'String'
    isDefault: 'Boolean'
    label: 'String'
    modifiedAt: 'DateTime'
    project: 'Project'
  }
  SubmissionTrackInteraction: { // field return type name
    city: 'String'
    country: 'String'
    countryCode: 'String'
    createdAt: 'DateTime'
    id: 'String'
    locationIp: 'String'
    playEnd: 'Int'
    playStart: 'Int'
    submissionTrack: 'SubmissionTrack'
    type: 'SubmissionTrackInteractionEvent'
  }
  Track: { // field return type name
    displayTitle: 'String'
    downloadUrl: 'String'
    duration: 'Int'
    format: 'String'
    id: 'String'
    isDeleted: 'Boolean'
    license: 'String'
    size: 'Int'
    state: 'TrackProcessingState'
    streamUrl: 'String'
    trackKey: 'String'
    user: 'User'
    waveformData: 'String'
    waveformId: 'String'
    waveformKey: 'String'
    waveformUrl: 'String'
  }
  User: { // field return type name
    email: 'String'
    id: 'String'
    isGuest: 'Boolean'
    name: 'String'
    profile: 'Profile'
    projects: 'Project'
    role: 'UserRole'
    type: 'UserType'
    username: 'String'
  }
}

export interface NexusGenArgTypes {
  Mutation: {
    createFeedbackTemplate: { // args
      input: NexusGenInputs['CreateSubmissionTrackFeedbackTemplateInput']; // CreateSubmissionTrackFeedbackTemplateInput!
    }
    createGuestUser: { // args
      email: string; // String!
      name: string; // String!
    }
    createProject: { // args
      name: string; // String!
      slug?: string | null; // String
    }
    createStack: { // args
      input: NexusGenInputs['CreateStackInput']; // CreateStackInput!
    }
    createStripeCheckoutBillingPortalUrl: { // args
      projectId: string; // String!
    }
    createStripeCheckoutSession: { // args
      plan: NexusGenEnums['PaidPlan']; // PaidPlan!
      projectId: string; // String!
    }
    createSubmissionTrackInteraction: { // args
      input: NexusGenInputs['SubmissionTrackInteractionInput']; // SubmissionTrackInteractionInput!
    }
    declineSubmissionTrack: { // args
      input: NexusGenInputs['DeclineSubmissionTrackInput']; // DeclineSubmissionTrackInput!
    }
    deleteTrackByKey: { // args
      trackKey: string; // String!
    }
    inviteToProject: { // args
      email: string; // String!
      projectId: string; // String!
    }
    moveSubmissionTrack: { // args
      stackId: string; // String!
      submissionTrackId: string; // String!
    }
    processTrackUploads: { // args
      input: NexusGenInputs['ProcessTrackUploadInput']; // ProcessTrackUploadInput!
    }
    removeUserFromProject: { // args
      projectId: string; // String!
      userId: string; // String!
    }
    sendSubmission: { // args
      input: NexusGenInputs['SendSubmissionInput']; // SendSubmissionInput!
    }
    shortlistSubmissionTrack: { // args
      input: NexusGenInputs['ShortlistSubmissionTrackInput']; // ShortlistSubmissionTrackInput!
    }
    startTrackUpload: { // args
      input: NexusGenInputs['StartTrackUploadInput']; // StartTrackUploadInput!
    }
    updateAsBusinessUser: { // args
      id: string; // String!
    }
    updateFeedbackTemplate: { // args
      id: string; // String!
      input: NexusGenInputs['UpdateSubmissionTrackFeedbackTemplateInput']; // UpdateSubmissionTrackFeedbackTemplateInput!
    }
    updateFeedbackTemplateAsDefault: { // args
      defaultFeedbackTemplateId: string; // String!
      updatableFeedbackTemplateId: string; // String!
    }
    updateStack: { // args
      id: string; // String!
      input: NexusGenInputs['UpdateStackInput']; // UpdateStackInput!
    }
    updateTrack: { // args
      id: string; // String!
      input: NexusGenInputs['UpdateTrackInput']; // UpdateTrackInput!
    }
    updateUser: { // args
      input?: NexusGenInputs['UpdateUserInput'] | null; // UpdateUserInput
    }
    upsertUser: { // args
      input?: NexusGenInputs['UpsertUserInput'] | null; // UpsertUserInput
    }
  }
  Project: {
    feedbackTemplates: { // args
      after?: NexusGenInputs['SubmissionTrackFeedbackTemplateWhereUniqueInput'] | null; // SubmissionTrackFeedbackTemplateWhereUniqueInput
      before?: NexusGenInputs['SubmissionTrackFeedbackTemplateWhereUniqueInput'] | null; // SubmissionTrackFeedbackTemplateWhereUniqueInput
      first?: number | null; // Int
      last?: number | null; // Int
    }
    stacks: { // args
      after?: NexusGenInputs['StackWhereUniqueInput'] | null; // StackWhereUniqueInput
      before?: NexusGenInputs['StackWhereUniqueInput'] | null; // StackWhereUniqueInput
      first?: number | null; // Int
      last?: number | null; // Int
    }
    submissionTracks: { // args
      after?: NexusGenInputs['SubmissionTrackWhereUniqueInput'] | null; // SubmissionTrackWhereUniqueInput
      before?: NexusGenInputs['SubmissionTrackWhereUniqueInput'] | null; // SubmissionTrackWhereUniqueInput
      first?: number | null; // Int
      last?: number | null; // Int
      orderBy?: NexusGenInputs['SubmissionTrackOrderByInput'][] | null; // [SubmissionTrackOrderByInput!]
      where?: NexusGenInputs['SubmissionTrackWhereInput'] | null; // SubmissionTrackWhereInput
    }
    submissions: { // args
      after?: NexusGenInputs['SubmissionWhereUniqueInput'] | null; // SubmissionWhereUniqueInput
      before?: NexusGenInputs['SubmissionWhereUniqueInput'] | null; // SubmissionWhereUniqueInput
      first?: number | null; // Int
      last?: number | null; // Int
      orderBy?: NexusGenInputs['SubmissionOrderByInput'][] | null; // [SubmissionOrderByInput!]
      where?: NexusGenInputs['SubmissionWhereInput'] | null; // SubmissionWhereInput
    }
    users: { // args
      after?: NexusGenInputs['UserWhereUniqueInput'] | null; // UserWhereUniqueInput
      before?: NexusGenInputs['UserWhereUniqueInput'] | null; // UserWhereUniqueInput
      first?: number | null; // Int
      last?: number | null; // Int
    }
  }
  Query: {
    project: { // args
      id?: string | null; // String
      slug?: string | null; // String
    }
    stack: { // args
      id: string; // String!
    }
    submission: { // args
      id: string; // String!
    }
    submissionTrack: { // args
      id: string; // String!
    }
    track: { // args
      id: string; // String!
    }
    userBySlug: { // args
      slug?: string | null; // String
    }
  }
  Stack: {
    submissionTracks: { // args
      after?: NexusGenInputs['SubmissionTrackWhereUniqueInput'] | null; // SubmissionTrackWhereUniqueInput
      before?: NexusGenInputs['SubmissionTrackWhereUniqueInput'] | null; // SubmissionTrackWhereUniqueInput
      first?: number | null; // Int
      last?: number | null; // Int
      orderBy?: NexusGenInputs['SubmissionTrackOrderByInput'][] | null; // [SubmissionTrackOrderByInput!]
      where?: NexusGenInputs['SubmissionTrackWhereInput'] | null; // SubmissionTrackWhereInput
    }
  }
  Submission: {
    submissionTracks: { // args
      after?: NexusGenInputs['SubmissionTrackWhereUniqueInput'] | null; // SubmissionTrackWhereUniqueInput
      before?: NexusGenInputs['SubmissionTrackWhereUniqueInput'] | null; // SubmissionTrackWhereUniqueInput
      first?: number | null; // Int
      last?: number | null; // Int
      orderBy?: NexusGenInputs['SubmissionTrackOrderByInput'][] | null; // [SubmissionTrackOrderByInput!]
      where?: NexusGenInputs['SubmissionTrackWhereInput'] | null; // SubmissionTrackWhereInput
    }
  }
  SubmissionTrack: {
    submissionTrackInteractions: { // args
      after?: NexusGenInputs['SubmissionTrackInteractionWhereUniqueInput'] | null; // SubmissionTrackInteractionWhereUniqueInput
      before?: NexusGenInputs['SubmissionTrackInteractionWhereUniqueInput'] | null; // SubmissionTrackInteractionWhereUniqueInput
      first?: number | null; // Int
      last?: number | null; // Int
    }
  }
  SubmissionTrackFeedback: {
    comments: { // args
      after?: NexusGenInputs['CommentWhereUniqueInput'] | null; // CommentWhereUniqueInput
      before?: NexusGenInputs['CommentWhereUniqueInput'] | null; // CommentWhereUniqueInput
      first?: number | null; // Int
      last?: number | null; // Int
    }
    submissionTrack: { // args
      after?: NexusGenInputs['SubmissionTrackWhereUniqueInput'] | null; // SubmissionTrackWhereUniqueInput
      before?: NexusGenInputs['SubmissionTrackWhereUniqueInput'] | null; // SubmissionTrackWhereUniqueInput
      first?: number | null; // Int
      last?: number | null; // Int
    }
  }
  User: {
    projects: { // args
      after?: NexusGenInputs['ProjectWhereUniqueInput'] | null; // ProjectWhereUniqueInput
      before?: NexusGenInputs['ProjectWhereUniqueInput'] | null; // ProjectWhereUniqueInput
      first?: number | null; // Int
      last?: number | null; // Int
    }
  }
}

export interface NexusGenAbstractTypeMembers {
}

export interface NexusGenTypeInterfaces {
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = keyof NexusGenInputs;

export type NexusGenEnumNames = keyof NexusGenEnums;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = never;

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    isTypeOf: false
    resolveType: true
    __typename: false
  }
}

export interface NexusGenTypes {
  context: GraphQLContext;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
    /**
     * Authorization for an individual field. Returning "true"
     * or "Promise<true>" means the field can be accessed.
     * Returning "false" or "Promise<false>" will respond
     * with a "Not Authorized" error for the field.
     * Returning or throwing an error will also prevent the
     * resolver from executing.
     */
    authorize?: FieldAuthorizeResolver<TypeName, FieldName>
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}